src/models/bodegas.py
from sqlalchemy import Column, String, Numeric, Sequence, Date
from sqlalchemy.schema import PrimaryKeyConstraint, ForeignKeyConstraint
from src.database.db import db

class Bodegas(db.Model):
    __tablename__ = 'bodegas'
    
    id_pais_pro = Column(Numeric(3), primary_key=True)
    id_region = Column(Numeric(3), primary_key=True)
    id_bodega = Column(Numeric(3), primary_key=True, default=Sequence('seq_bodega'))
    nombre = Column(String(50), nullable=False, unique=True)
    historia = Column(String(1500), nullable=False)
    enlace_web = Column(String(50), nullable=False, unique=True)
    direccion = Column(String(200), nullable=False, unique=True)
    fecha_fundacion = Column(Date, nullable=False)
    resumen_vinos = Column(String(1500), nullable=False)

    __table_args__ = (
        ForeignKeyConstraint(['id_pais_pro', 'id_region'], ['regiones.id_pais_pro', 'regiones.id_region'], name='fk_bodega_region'),
        PrimaryKeyConstraint('id_pais_pro', 'id_region', 'id_bodega', name='pk_bodega'),
    )

    def __init__(self, id_pais_pro, id_region, nombre, historia, enlace_web, direccion, fecha_fundacion, resumen_vinos):
        self.id_pais_pro = id_pais_pro
        self.id_region = id_region
        self.nombre = nombre
        self.historia = historia
        self.enlace_web = enlace_web
        self.direccion = direccion
        self.fecha_fundacion = fecha_fundacion
        self.resumen_vinos = resumen_vinos

src/routes/anada.py
from flask import Blueprint, render_template, request, flash, redirect, url_for, jsonify
from sqlalchemy.orm import Session
from src.database.db import db
from sqlalchemy import select, text

# Entidades
from src.models.bodegas import Bodegas
from src.models.vino_marca import VinoMarca

# //

ana = Blueprint('anada', __name__)

# Agregar Bodega
@ana.route('/add_anada', methods=['GET','POST'])
def addAnada():
    
    session = Session(bind=db.engine)
    
    get_vin = VinoMarca.query.all()
    bodega_name = '-'
    
    if request.method == "POST":
        
        try:   
            # Comenzar una nueva transaccion
            session.begin()
            
            _id_vino = request.form['ana-id-vino']
            _id_pais_pro = session.execute(select(VinoMarca.id_pais_pro).where(VinoMarca.id_vino == _id_vino)).scalar()
            _id_region = session.execute(select(VinoMarca.id_region).where(VinoMarca.id_vino == _id_vino)).scalar()
            _id_bodega = session.execute(select(VinoMarca.id_bodega).where(VinoMarca.id_vino == _id_vino)).scalar()

            bodega_name = session.execute(select(Bodegas.nombre).where(Bodegas.id_bodega == _id_bodega)).scalar()

            
            _ano_produccion = (request.form['ana-ano-produccion'] + "-01-01")
            _botellas_producidas = request.form['ana-botellas-producidas']
            _total_dest_exp_hl = request.form['ana-total-dest-exp-hl']
            _clasificacion_anada = request.form['ana-clasificacion-anada']
            
            
            session.execute(text("SELECT insert_into_produccion(:id_pais_pro, :id_region, :id_bodega, :id_vino, :ano_produccion, :botellas_producidas, :total_dest_exp_hl, :clasificacion_anada)"), 
            {
                'id_pais_pro': _id_pais_pro,
                'id_region': _id_region,
                'id_bodega': _id_bodega,
                'id_vino': _id_vino,
                'ano_produccion': _ano_produccion,
                'botellas_producidas': _botellas_producidas,
                'total_dest_exp_hl': _total_dest_exp_hl,
                'clasificacion_anada': _clasificacion_anada
            })
            
            session.commit()    
        except:
            session.rollback()
            raise
        finally:
            session.close()

        return redirect(url_for('index.index'))
    else:
        return render_template('anada.html', get_vin=get_vin, bodega_name=bodega_name)
# //   

@ana.route('/get_bodega_name', methods=['POST'])
def get_bodega_name():
    _id_vino = request.form['ana-id-vino']
    _id_bodega = select(VinoMarca.id_bodega).where(VinoMarca.id_vino == _id_vino).scalar_subquery()
    
    bodega_name = db.session.execute(select(Bodegas.nombre).where(Bodegas.id_bodega == _id_bodega)).scalar()
    return jsonify(bodega_name=bodega_name)

src/routes/bodega.py
from flask import Blueprint, render_template, request, flash, jsonify, redirect, url_for
from sqlalchemy import select, text
from sqlalchemy.orm import Session
from src.database.db import db

# Entidades
from src.models.regiones import Regiones
from src.models.paises_productores import PaisesProductores
# //

bod = Blueprint('bodega', __name__)

# FIXME: Falta arreglar los estilos de telefono

# Agregar Bodega
@bod.route('/add_bodega', methods=['GET','POST'])
def addBodega():

    session = Session(bind=db.engine)
    
    get_pai = PaisesProductores.query.all()
    
    if request.method == "POST":
        
        try:
            # Comenzar una nueva transaccion
            session.begin()
        
            # Obtencion de la PK del pais
            _nombrePai = request.form['bod-nombrePai']
            _id_pais_pro = db.session.execute(select(PaisesProductores.id_pais_pro).where(PaisesProductores.nombre == _nombrePai)).scalar_one()

            # Obtencion de PK de la region
            _nombreReg = request.form['bod-nombreReg']
            _id_region = db.session.execute(select(Regiones.id_region).where(Regiones.nombre == _nombreReg)).scalar_one()
            
            # Atributos de bodega
            _nombre =  request.form['bod-nombre']
            _historia = request.form['bod-historia']
            _enlace_web = request.form['bod-enlace_web']
            _direccion = request.form['bod-direccion']
            _fecha_fundacion = request.form['bod-fecha_fundacion']
            _resumen_vinos = request.form['bod-resumen_vinos']
            # //
                    
            # Atributos de telefono
            _codigo_area = list(map(int, request.form.getlist('tlf-codigo-area[]')))
            _numero = list(map(int, request.form.getlist('tlf-numero[]')))
            
            session.execute(text("SELECT insert_into_bod_tel(:id_region, :id_pais_pro, :nombre, :historia, :enlace_web, :direccion, :fecha_fundacion, :resumen_vinos, :codigo_area, :numero)"), 
                {"id_region": _id_region, 
                 "id_pais_pro": _id_pais_pro, 
                 "nombre": _nombre, 
                 "historia": _historia, 
                 "enlace_web": _enlace_web, 
                 "direccion": _direccion, 
                 "fecha_fundacion": _fecha_fundacion, 
                 "resumen_vinos": _resumen_vinos, 
                 "codigo_area": _codigo_area, 
                 "numero": _numero})
            # //
            
            session.commit()
        except:
            session.rollback()
            raise
        finally:
            session.close()

        return redirect(url_for('index.index'))
    else:
        return render_template('bodega.html', get_pai=get_pai)
# //   

# Obtener regiones
@bod.route('/get_regions', methods=['POST'])
def get_regions():
    _nombrePai = request.form.get('bod-nombrePai')
    _id_pais_pro = select(PaisesProductores.id_pais_pro).where(PaisesProductores.nombre == _nombrePai).scalar_subquery()
    
    get_reg = Regiones.query.filter_by(id_pais_pro=_id_pais_pro).all()
    return jsonify([region.nombre for region in get_reg])
# //

src/routes/catalogo.py
from flask import Blueprint, render_template, request, send_file, jsonify, redirect, url_for
from sqlalchemy import select, or_, and_, distinct, text
from sqlalchemy.orm import Session
from sqlalchemy.orm import aliased
from src.database.db import db


# Entidades
from src.models.bodegas import Bodegas
from src.models.vino_marca import VinoMarca
from src.models.presentacion import Presentacion
from src.models.variedad_vino import VariedadVino
from src.models.vitis_vinifera import VitisVinifera
from src.models.clasificaciones import Clasificaciones
# //

cat = Blueprint('catalogo', __name__)


# Agregar Bodega
@cat.route('/add_catalogo', methods=['GET','POST'])
def addCatalogo():
    
    session = Session(bind=db.engine)
    
    get_bod = Bodegas.query.all()
        
    get_tipo1 = Clasificaciones.query.filter(or_(Clasificaciones.nivel == 1, Clasificaciones.id_clasificacion == 140)).all()
    get_pre = db.session.query(distinct(Presentacion.tipo)).all()
    get_pre = [t[0] for t in get_pre]
    get_uva = VitisVinifera.query.all()
    
    if request.method == "POST":
        
        
        try:
            # Comenzar una nueva transaccion
            session.begin()
            
            # Captura de datos general
            _nombreBod = request.form['cat-nombreBod']
            _id_bodega = db.session.query(Bodegas.id_bodega).filter(Bodegas.nombre == _nombreBod).scalar()
            _id_pais_pro = db.session.query(Bodegas.id_pais_pro).filter(Bodegas.id_bodega == _id_bodega).scalar()
            _id_region = db.session.query(Bodegas.id_region).filter(Bodegas.id_bodega == _id_bodega).scalar()
            
            # Clasificacion
            _id_Clasificacion = int(request.form.get('cat-nombreCla2'))
        
            # Captura de datos de vino_marca
            _nombre = request.form['cat-nombre']
            _meses_maduracion = int(request.form['cat-meses-maduracion'])
            _elaboracion = request.form['cat-elaboracion']
            _maridaje = request.form['cat-maridaje']
            _promedio_anos_consumo = int(request.form['cat-promedio-anos-consumo'])
            _temp_servicio = int(request.form['cat-temp-servicio'])
            _ph = float(request.form['cat-ph'])
            _descripcion_cata = request.form['cat-descripcion-cata']
            _grado_alcohol = float(request.form['cat-grado-alcohol'])
            _acidez = float(request.form['cat-acidez'])
            _imagen_vino = request.files['cat-imagen-vino']
                    
            _imagen_data = _imagen_vino.read()
        
            # Captura de datos de Presentacion
            _tipo = request.form.getlist('cat-tipo[]')
            _descripcion = request.form.getlist('cat-descripcion[]')
            _cantidad_botellas = list(map(int, request.form.getlist('cat-cantidad-botellas[]')))
            
            # Captura de datos de Variedad
            _id_uva = request.form.getlist('cat-nombre-variedad[]')

            session.execute(text("SELECT insert_into_vino_presentacion_variedad(:id_pais_pro, :id_region, :id_bodega, :nombre, :meses_maduracion, :elaboracion, :maridaje, :promedio_anos_consumo, :temp_servicio, :ph, :descripcion_cata, :grado_alcohol, :acidez, :imagen_data, :id_clasificacion, :tipo, :descripcion, :cantidad_botellas, :id_uva)"), 
            {
                "id_pais_pro": _id_pais_pro,
                "id_region": _id_region,
                "id_bodega": _id_bodega,
                "nombre": _nombre,
                "meses_maduracion": _meses_maduracion,
                "elaboracion": _elaboracion,
                "maridaje": _maridaje,
                "promedio_anos_consumo": _promedio_anos_consumo,
                "temp_servicio": _temp_servicio,
                "ph": _ph,
                "descripcion_cata": _descripcion_cata,
                "grado_alcohol": _grado_alcohol,
                "acidez": _acidez,
                "imagen_data": _imagen_data,
                "id_clasificacion": _id_Clasificacion,
                "tipo": _tipo,
                "descripcion": _descripcion,
                "cantidad_botellas": _cantidad_botellas,
                "id_uva": _id_uva
            })
            # //
            session.commit()
        except:
            session.rollback()
            raise
        finally:
            session.close()
        
        
        return redirect(url_for('index.index'))
    else:
        return render_template('catalogo.html', get_bod=get_bod, get_tipo1=get_tipo1, get_pre=get_pre, get_uva=get_uva)
# //   

# Obtener las subclasificaciones
@cat.route('/get_clas', methods=['POST'])
def get_clas():
    
    # Crear un alias para la tabla Clasificaciones
    ClasificacionesAlias = aliased(Clasificaciones)
    
    _nombreCla1 = request.form['cat-nombreCla']
    _id_Clasificacion1 = select(Clasificaciones.id_clasificacion).where(Clasificaciones.nombre == _nombreCla1).scalar_subquery()
    
    get_tipo2 = db.session.query(
        Clasificaciones.nombre, Clasificaciones.id_clasificacion
    ).join(
        ClasificacionesAlias, 
       _id_Clasificacion1 == Clasificaciones.id_padre_clasificacion
    ).filter(
        and_(ClasificacionesAlias.nombre == _nombreCla1, Clasificaciones.nombre != 'ESPECIALES')
    ).all()
    
    return jsonify([(clasificacion.nombre.capitalize(), clasificacion.id_clasificacion) for clasificacion in get_tipo2])
# //

templates/add_bodega.html
{% extends 'layout.html' %}

{% block title %}Registro Bodega{% endblock %}

{% block body %}

<!-- Action form -->
<div style="display: flex; justify-content: center; align-items: center;">
  <form action="/add_bodega" method="POST" class="form-control" style="background-color: transparent; color: #fff; padding: 20px; border: none; max-width: 400px;" enctype="multipart/form-data">

    <div class="form-group" style="display: flex; flex-direction: column;">
      <label for="bod-nombre">Nombre</label>
      <input type="text" class="form-control" id="bod-nombre" placeholder="Enter name" name="bod-nombre" required>
    </div>
    
    <div class="form-group" style="display: flex; flex-direction: column;">
      <label for="bod-historia">Historia</label>
      <input type="text" class="form-control" id="bod-historia" placeholder="Enter history" name="bod-historia" required>
    </div>
    
    <div class="form-group" style="display: flex; flex-direction: column;">
      <label for="bod-direccion_web">Web</label>
      <input type="text" class="form-control" id="bod-direccion_web" placeholder="Enter URL" name="bod-direccion_web" required>
    </div>
    
    <div class="form-group" style="display: flex; flex-direction: column;">
      <label for="bod-id_region">Region</label>
      <select class="form-control" id="bod-id_region" name="bod-id_region" required>
        <option value="" style="color: black;">Escoger Region</option>
        {% for region in regiones %}
          <option value="{{ region.id_region }}" style="color: black;">{{ region.nombre }}</option>
        {% endfor %}
      </select>
    </div>
    
    <div class="form-group" style="display: flex; flex-direction: column;">
      <label for="bod-imagen">Imagen</label>
      <input type="file" class="form-control" id="bod-imagen" name="bod-imagen" required>
    </div>

    <button type="submit" class="btn btn-dark">Aceptar</button>

  </form>
</div>


{% endblock body %}

templates/anada.html
{% extends 'layout.html' %}

{% block title %}Añada{% endblock %}

{% block body %}
<link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='css/anada.css') }}">

<!-- Navbar -->
<nav class="navbar">
      
  <!-- logo -->
  <a href="{{ url_for('index.index') }}" style="pointer-events: auto;">
      <div href="{{ url_for('index.index') }}" class="nav-logo" style="width: 7rem;" style="pointer-events: auto;">
          {% block logo %}<object class="logo" href="{{ url_for('index.index') }}" data="{{ url_for('static', filename='img/LogoBlack.svg') }}" type="image/svg+xml" style="pointer-events: none;"></object>{% endblock %}
      </div>
  </a>
  <!-- // -->

  <div class="nav-items">
      <!-- Enlaces de navegacion -->
      <a class="nav-item" href="{{ url_for('bodega.addBodega') }}">Bodega</a>
      <a class="nav-item" href="{{ url_for('catalogo.addCatalogo') }}">Catálogo</a>
      <a class="nav-item" href="{{ url_for('anada.addAnada') }}">Añada</a>
  </div>
      
  <!-- // -->
</div>
</nav>


<!-- Action form -->
<form action="{{ url_for('anada.addAnada') }}" method="POST" class="form-control">
    
    <div class="anada-info">  
        <label class="top-label">Informacion Produccion</label>  
        <div class="form-row">
            <div class="form-group">
                <label>Vino</label>
                <select id="ana-id-vino" name="ana-id-vino">
                <option value="">Selecciona un vino</option>
                {% for vino in get_vin %}
                    <option value="{{ vino.id_vino }}">{{ vino.nombre }}</option>
                {% endfor %}
                </select>
            </div>

            <div class="nombre-bod">
                <label for="ana-ano-produccion">Bodega</label>
                <div id="bodega-name">{{ bodega_name }}</div>
            </div>
        </div>

        <label for="ana-ano-produccion">Año de Producción</label>
        <input type="text" id="ana-ano-produccion" name="ana-ano-produccion" placeholder="Año de producción" required>

        <label for="ana-botellas-producidas">Botellas Producidas</label>
        <input type="number" id="ana-botellas-producidas" name="ana-botellas-producidas" placeholder="Número de botellas producidas" required>

        <label for="ana-total-dest-exp-hl">Total Destinado a Exportación (hl)</label>
        <input type="number" id="ana-total-dest-exp-hl" name="ana-total-dest-exp-hl" placeholder="Total destinado a exportación en hectolitros" required>

        <label for="ana-clasificacion-ana">Clasificación de la Añada</label>
        <select id="ana-clasificacion-ana" name="ana-clasificacion-anada" required>
            <option value="">Selecciona una clasificación</option>
            <option value="MB">Muy Buena</option>
            <option value="B">Buena</option>
            <option value="E">Excelente</option>
        </select>
    </div>

    <div class="button-container">
        <button class="submit-btn" type="submit">Aceptar</button>
    </div>

</form>

<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
<script>

// Para conseguir el nombre
$(document).ready(function(){
  $("#ana-id-vino").change(function(){
    var id_vino = $(this).val();
    $.post("{{ url_for('anada.get_bodega_name') }}", {'ana-id-vino': id_vino}, function(data){
      $("#bodega-name").text(data.bodega_name);
    });
  });
});
// //

// Para extraer la fecha
var input = document.getElementById('ana-ano-produccion');
    input.addEventListener('input', function () {
        if (this.value.length > 4) 
            this.value = this.value.slice(0,4); 
    })
// //

</script>

{% endblock body %}

templates/bodega.html
{% extends 'layout.html' %}

{% block title %}Bodega{% endblock %}


{% block body %}
<link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='css/bodega.css') }}">

<!-- Navbar -->
<nav class="navbar">
      
  <!-- logo -->
  <a href="{{ url_for('index.index') }}" style="pointer-events: auto;">
      <div href="{{ url_for('index.index') }}" class="nav-logo" style="width: 7rem;" style="pointer-events: auto;">
          {% block logo %}<object class="logo" href="{{ url_for('index.index') }}" data="{{ url_for('static', filename='img/LogoBlack.svg') }}" type="image/svg+xml" style="pointer-events: none;"></object>{% endblock %}
      </div>
  </a>
  <!-- // -->

  <div class="nav-items">
      <!-- Enlaces de navegacion -->
      <a class="nav-item" href="{{ url_for('bodega.addBodega') }}">Bodega</a>
      <a class="nav-item" href="{{ url_for('catalogo.addCatalogo') }}">Catálogo</a>
      <a class="nav-item" href="{{ url_for('anada.addAnada') }}">Añada</a>
  </div>
      
  <!-- // -->
</div>
</nav>

<!-- Action form -->
<form action="{{ url_for('bodega.addBodega') }}" method="POST" class="form-control">
    
  <!-- Informacion General -->
  <div class="info-general">
    <div class="left-column">

      <label class="main-label">Informacion General</label>

      <div class="inputs">
        <div class="form-group">
          <label for="bod-nombre">Nombre</label>
          <input type="text" id="bod-nombre" name="bod-nombre" required>
        </div>
    
        <div class="form-group">
          <label for="bod-enlace_web">Enlace Web</label>
          <input type="text" id="bod-enlace_web" name="bod-enlace_web" required>
        </div>
    
        <div class="form-group">
          <label for="bod-fecha_fundacion">Fecha de Fundacion</label>
          <input type="date" id="bod-fecha_fundacion" name="bod-fecha_fundacion" required>
        </div>
      </div>
    
    </div>

    <div class="right-column">
      <div class="form-group">
        <label for="bod-historia">Historia</label>
        <textarea id="bod-historia" name="bod-historia" required></textarea>
      </div>

      <div class="form-group">
        <label for="bod-direccion">Direccion</label>
        <input type="text" id="bod-direccion" name="bod-direccion" required>
      </div>

      <div class="form-group">
        <label for="bod-resumen_vinos">Resumen de Vinos</label>
        <textarea id="bod-resumen_vinos" name="bod-resumen_vinos" required></textarea>
      </div>
    </div>
  </div>
  <!-- // -->

  <!-- Informacion de Contacto -->
  <div class="info-contacto">
    <div class="left-column">
      <label class="main-label">Informacion de Contacto</label>
      <!-- Zona de telefono -->
      <div id="telefonos">
          <div class="telefono">
              <label for="tlf-codigo-area">Codigo de Area</label>
              <input type="text" id="tlf-codigo-area" name="tlf-codigo-area[]" placeholder="Codigo de Area" required>

              <label for="tlf-numero">Numero</label>
              <input type="text" id="tlf-numero" name="tlf-numero[]" placeholder="Numero" required>
          </div>
      </div>
      <button type="button" id="add-telefono">Agregar otro telefono</button>
      <!-- // -->
    </div>

    <!-- Columna derecha contacto -->
    <div class="right-column">
      
      <!-- Combobox Pais -->
      <div class="form-group">
        <label>Pais</label>
        <select id="bod-nombrePai" name="bod-nombrePai">
          <option value="">Selecciona un país</option>
          {% for pais in get_pai %}
              <option value="{{ pais.nombre }}">{{ pais.nombre }}</option>
          {% endfor %}
        </select>
      </div>
      <!-- // -->

      <div class="form-group">
        <label>Region</label>
        <select id="bod-nombreReg" name="bod-nombreReg">
          <option value="">Selecciona una region</option>
          {% for region in get_reg %}
              <option value="{{ region.nombre }}">{{ region.nombre }}</option>
          {% endfor %}
        </select>
      </div>

    </div>
  </div>
  <!-- // -->

  <div class="button-container">
    <button class="submit-btn" type="submit">Aceptar</button>
  </div>
</form>

<!-- ZONA DE SCRIPTS -->
<!-- Query para que funcione el seleccionar regiones -->
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
<script>
$(document).ready(function() {
    $('#bod-nombrePai').change(function() {
        var selectedCountry = $(this).val();
        $.ajax({
            url: '{{ url_for("bodega.get_regions") }}',
            data: { 'bod-nombrePai': selectedCountry },
            type: 'POST',
            success: function(response) {
                var regionsSelect = $('#bod-nombreReg');
                regionsSelect.empty();
                $.each(response, function(index, region) {
                    regionsSelect.append($('<option></option>').attr('value', region).text(region));
                });
            },
            error: function(error) {
                console.log(error);
            }
        });
    });
});
// //

// Query para agregar telefonos
// Para que funcione la entrada multiple de datos en telefono
var telefonoIndex = 0;

document.getElementById('add-telefono').addEventListener('click', function() {
    var telefonos = document.getElementById('telefonos');
    var newTelefono = document.createElement('div');
    newTelefono.className = 'telefono';
    newTelefono.innerHTML = `
        <label for="tlf-codigo-area-">Codigo de Area</label>
        <input type="text" id="tlf-codigo-area-" name="tlf-codigo-area[]" placeholder="Codigo de Area" required>

        <label for="tlf-numero-">Numero</label>
        <input type="text" id="tlf-numero-" name="tlf-numero[]" placeholder="Numero" required>
        <button type="button" class="remove-telefono">Eliminar</button>
    `;
    telefonos.appendChild(newTelefono);
    telefonoIndex++;
});
// //

// Remover un elemento telefono
document.getElementById('telefonos').addEventListener('click', function(e) {
    if (e.target && e.target.classList.contains('remove-telefono')) {
        e.target.parentNode.remove();
    }
});
// //
</script>

<!-- // -->

{% endblock body %}

templates/index.html
<head>
    <!-- Tipografia -->
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Alegreya+Sans:wght@100;300;400;500;700&display=swap" rel="stylesheet">
    <!-- // -->

    <!-- Archivos Internos CSS-->
    <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='css/layout.css') }}">
    <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='css/index.css') }}">
    <!-- // -->
</head> 

<body>

    <!-- Navbar -->
    <nav class="nav-bar">
        <div class="container">
            <a href="{{ url_for('index.index') }}" style="pointer-events: auto;">
                <div class="nav-logo" style="width: 5rem;">
                    <object class="logo" href="../src/routes/index.py" data="{{ url_for('static', filename='img/LogoBlack.svg') }}" type="image/svg+xml"></object>
                </div>
            </a>

            <!-- center items -->
            <div class="container-midle">
                <div class="nav-link">
                    <a href="{{ url_for('bodega.addBodega') }}">Bodega</a>
                </div>
                
                <div class="nav-link">
                    <a href="{{ url_for('catalogo.addCatalogo') }}">Catálogo</a>
                </div>
            </div>
            <!-- // -->
            
            <div class="nav-link">
                <a href="{{ url_for('anada.addAnada') }}">Añada</a>
            </div>

        </div>
    </nav>

    <!-- Video de fondo -->
    <div class="video-container">
        <video src="../static/video/wineVideo.mp4" autoplay loop muted></video>
    </div>
    <!-- // -->

</body>
    

templates/layout.html
<!DOCTYPE html>
<html lang="es">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <!-- Title -->
    <title>{% block title %}{% endblock %}</title>
    <!-- // -->

    <!-- Browser tab icon -->
    <link rel="shortcut icon" type="x-icon" href="/static/img/favicon.svg">
    <!-- // -->

    <!-- Tipografia -->
        
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Alegreya+Sans:wght@100;300;400;500;700&display=swap" rel="stylesheet">
    <!-- // -->

    <!-- Archivos Internos -->
    <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='css/layout.css') }}">
    <!-- // -->
    
</head>

<body>    


    {% block body %}
    {% endblock %}

    <script>
        function guardarSeleccion(value) {
            $.ajax({
                url: '/add_bodega',
                type: 'POST',
                data: { 'bod-id_region': value },
                success: function(response) {
                    console.log(response);
                },
                error: function(error) {
                    console.log(error);
                }
            });
        }
    </script>
</body>

</html>